# Generated by Django 3.2 on 2021-04-20 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_client_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date_devolution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='date_loan',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
