# Generated by Django 3.2 on 2021-04-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210419_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='date_loan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
